CREATE TABLE IF NOT EXISTS `users` (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
mobile VARCHAR(15) UNIQUE,
password VARCHAR(255),
photo VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS `login` (
id INT AUTO_INCREMENT PRIMARY KEY,
mobile VARCHAR(15) UNIQUE,
password VARCHAR(255)
);

CREATE TABLE notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100),
    lot VARCHAR(50),
    bundle VARCHAR(50),
    pc INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `login_notifications` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50),
    message TEXT,
    status INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lots (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lot_name VARCHAR(50) NOT NULL,
    bundle VARCHAR(50) NOT NULL,
    pc INT NOT NULL,
    username VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS operations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lot_id INT NOT NULL,
    operation_name VARCHAR(100),
    rate DECIMAL(5,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lot_id) REFERENCES lots(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `admin_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin_id` INT NOT NULL,
  `action` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`admin_id`) REFERENCES `admins`(`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50),
    bundle VARCHAR(20),
    pc INT,
    lot VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);